package:
  name: azcopy
  version: 10.25.1
  epoch: 0
  description: The new Azure Storage data transfer utility
  copyright:
    - license: MIT

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/Azure/azure-storage-azcopy
      tag: v${{package.version}}
      expected-commit: d1863284328fcb4ba73c0d94d473f91c9d94f5aa

  - uses: go/build
    with:
      packages: .
      output: azcopy
      go-package: go

update:
  enabled: true
  github:
    identifier: Azure/azure-storage-azcopy
    strip-prefix: v

test:
  pipeline:
    - runs: |
        azcopy --version
