package:
  name: bincapz
  version: 0.13.2
  epoch: 1
  description: enumerate binary capabilities, including malicious behaviors
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle
      - yara

environment:
  contents:
    packages:
      - openssl-dev
      - yara-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/chainguard-dev/bincapz
      tag: v${{package.version}}
      expected-commit: ae3a08b68baed4025359a29bb7e34529107fda70

  - uses: go/build
    with:
      packages: .
      ldflags: -s -w
      output: bincapz

  - uses: strip

test:
  environment:
    contents:
      packages:
        - openssl
        - crane
  pipeline:
    - name: Verify bincapz on itself
      runs: |
        set -o pipefail
        output=$(bincapz /usr/bin/bincapz)
        test -z "$output"
    - name: Verify bincapz on yara
      runs: |
        set -o pipefail
        bincapz /usr/bin/yara | grep LOW
    - name: Verify bincapz on openssl
      runs: |
        set -o pipefail
        bincapz /usr/bin/openssl | grep MED
    - name: Verify bincapz on crane
      runs: |
        set -o pipefail
        bincapz /usr/bin/crane | grep MED
    - name: Verify bincapz diff
      runs: |
        set -o pipefail
        bincapz -diff /usr/bin/openssl /usr/bin/crane | grep "[+]MED.*archives/zip"

update:
  enabled: true
  github:
    identifier: chainguard-dev/bincapz
    strip-prefix: v
