package:
  name: buf
  version: 1.34.0
  epoch: 1
  description: A new way of working with Protocol Buffers.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/bufbuild/buf
      tag: v${{package.version}}
      expected-commit: 3b5b535e0cce4c8a16874000d8ece9498afeffeb

  - uses: go/build
    with:
      packages: ./cmd/buf
      modroot: .
      output: buf
      ldflags: -X main.version=${{package.version}} -X main.commit=$(git rev-parse HEAD) -X main.date=$(date ${SOURCE_DATE_EPOCH:+ -d@${SOURCE_DATE_EPOCH}} "+%Y-%m-%dT%H:%M:%SZ")

  - uses: strip

update:
  enabled: true
  github:
    strip-prefix: v
    identifier: bufbuild/buf
