package:
  name: cluster-api-controller
  version: 1.7.3
  epoch: 1
  description: Cluster API core controller
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      expected-commit: b0284d8b9bf1220b744e8cfbfc812321c733e2dd
      repository: https://github.com/kubernetes-sigs/cluster-api
      tag: v${{package.version}}

  - uses: go/build
    with:
      ldflags: -s -w
      output: cluster-api-controller
      packages: .

  - uses: strip

update:
  enabled: true
  github:
    identifier: kubernetes-sigs/cluster-api
    strip-prefix: v
    tag-filter: v
    use-tag: true
