package:
  name: dbmate
  version: 2.18.0
  epoch: 1
  description: A lightweight, framework-agnostic database migration tool.
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/amacneil/dbmate
      tag: v${{package.version}}
      expected-commit: 95b49f1f7c2d3ad8400f34f48115503f93d6105e

  - uses: go/build
    with:
      packages: ./
      ldflags: -s -w
      output: dbmate

  - uses: strip

update:
  enabled: true
  github:
    identifier: amacneil/dbmate
    strip-prefix: v

test:
  pipeline:
    - name: Verify dbmate installation
      runs: |
        dbmate --version
