package:
  name: fulcio
  version: 1.4.5
  epoch: 6
  description: Sigstore OIDC PKI
  copyright:
    - license: Apache-2.0

environment:
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 0ac692c4451021fff6d3305d7f77146ae24b9666
      repository: https://github.com/sigstore/fulcio
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: golang.org/x/net@v0.23.0 github.com/Azure/azure-sdk-for-go/sdk/azidentity@v1.6.0 github.com/hashicorp/go-retryablehttp@v0.7.7

  - uses: go/build
    with:
      ldflags: -s -w
      modroot: .
      output: fulcio
      packages: ./

  - uses: strip

update:
  enabled: true
  github:
    identifier: sigstore/fulcio
    strip-prefix: v
