package:
  name: gh
  version: 2.52.0
  epoch: 2
  description: GitHub's official command line tool
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 467550a14aa6e26f6872d684279e6604ed6ca7e7
      repository: https://github.com/cli/cli
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: github.com/hashicorp/go-retryablehttp@v0.7.7

  - runs: make install prefix=${{targets.destdir}}/usr

  - uses: strip

update:
  enabled: true
  github:
    identifier: cli/cli
    strip-prefix: v

test:
  pipeline:
    - runs: |
        gh --version
