# source is gitlab so we can't use github updates to get expected commit
# let's still auto create the PR, it will fail as expected commit will be wrong
# however it will be easy to fix
#nolint:git-checkout-must-use-github-updates
package:
  name: gitaly
  version: 17.1.0
  epoch: 1
  description:
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - busybox
      - go
      - make

pipeline:
  - uses: git-checkout
    with:
      repository: https://gitlab.com/gitlab-org/gitaly.git
      tag: v${{package.version}}
      expected-commit: 5f2de7a7e2cee5c84c446907508dae9e6e7ff445

  - uses: go/bump
    with:
      deps: github.com/Azure/azure-sdk-for-go/sdk/azidentity@v1.6.0 github.com/Azure/azure-sdk-for-go/sdk/azidentity@v1.6.0 github.com/Azure/azure-sdk-for-go/sdk/azidentity@v1.6.0

  - runs: |
      make install DESTDIR="${{targets.destdir}}" PREFIX=/usr

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 38196

test:
  pipeline:
    - runs: |
        gitaly -v | grep "${{package.version}}"
        gitaly-blackbox -version | grep "${{package.version}}"
        gitaly-backup -v | grep "${{package.version}}"
