package:
  name: gitlab-logger
  version: 3.0.0
  epoch: 10
  description: GitLab Logger provides a means of wrapping non-structured log files within structure JSON.
  copyright:
    - license: MIT

environment:
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://gitlab.com/gitlab-org/cloud-native/gitlab-logger
      expected-commit: 61e76054e898803f7c2408e7e54dfba96a5085fc
      tag: v${{package.version}}

  - uses: go/build
    with:
      packages: ./cmd/gitlab-logger
      output: gitlab-logger
      ldflags: -X main.version=${{package.version}} -X main.buildtime=$(date +%F-%T)

subpackages:
  - name: gitlab-logger-compat
    pipeline:
      - runs: |
          # GitLab helm chart mostly hardcodes multiple executables path to /usr/local/bin/*
          mkdir -p "${{targets.subpkgdir}}"/usr/local/bin
          ln -s /usr/bin/gitlab-logger "${{targets.subpkgdir}}"/usr/local/bin/gitlab-logger

update:
  enabled: true
  release-monitor:
    identifier: 373223

test:
  environment:
    contents:
      packages:
        - ${{package.name}}-compat
  pipeline:
    - runs: |
        gitlab-logger -h
