# source is gitlab so we can't use github updates to get expected commit
# let's still auto create the PR, it will fail as expected commit will be wrong
# however it will be easy to fix
#nolint:git-checkout-must-use-github-updates
package:
  name: gitlab-cng
  version: 17.1.1
  epoch: 1
  description: Cloud Native container images per component of GitLab
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - busybox

pipeline:
  - uses: git-checkout
    with:
      repository: https://gitlab.com/gitlab-org/build/CNG.git
      tag: v${{package.version}}
      expected-commit: 4e8323c1fa8a21d349dacb0c10b0620f59572dba

data:
  # Used to create all of the *-scripts subpackages from the CNG repo.
  - name: scripts
    items:
      cfssl-self-sign: ./cfssl-self-sign
      container-registry: ./gitlab-container-registry
      exporter: ./gitlab-exporter
      geo-logcursor: ./gitlab-geo-logcursor
      gitaly: ./gitaly
      mailroom: ./gitlab-mailroom
      pages: ./gitlab-pages
      rails: ./gitlab-rails
      shell: ./gitlab-shell
      sidekiq: ./gitlab-sidekiq
      toolbox: ./gitlab-toolbox
      webservice: ./gitlab-webservice
      workhorse: ./gitlab-workhorse

subpackages:
  - range: scripts
    name: "${{package.name}}-${{range.key}}-scripts"
    pipeline:
      - runs: |
          cd ${{range.value}}
          for x in $(find scripts/ -type f); do
            mkdir -p ${{targets.subpkgdir}}/$(dirname $x)
            cp -r $x ${{targets.subpkgdir}}/$x
          done

  - name: "${{package.name}}-base"
    pipeline:
      - runs: |
          cd ./gitlab-base
          for x in $(find scripts/ -type f); do
            mkdir -p ${{targets.subpkgdir}}/$(dirname $x)
            cp -r $x ${{targets.subpkgdir}}/$x
          done
    dependencies:
      runtime:
        - bash
        - busybox
        - ca-certificates-bundle
        - curl
        - gitlab-logger
        - gomplate
        - procps
        - xtail

  - name: "${{package.name}}-certificates"
    pipeline:
      - runs: |
          cd ./certificates
          for x in $(find scripts/ -type f); do
            mkdir -p ${{targets.subpkgdir}}/$(dirname $x)
            cp -r $x ${{targets.subpkgdir}}/$x
          done
          ./scripts/bundle-certificates
    dependencies:
      runtime:
        - ca-certificates
        - gitlab-cng-base
    test:
      pipeline:
        - name: Test bundle-certificates script
          runs: |
            # if bundle-certificates runs correctly, it dereferences symlinks outside of /etc/ssl/certs
            for f in /etc/ssl/certs/*.pem /etc/ssl/certs/*.crt; do
              if [ -L "$f" ]; then
                origin=$(readlink -f "$f")
                originPath=${origin%/*}
                if [ "$originPath" != "/etc/ssl/certs" ]; then
                  echo "Error: $f is a symlink pointing outside of /etc/ssl/certs to $origin"
                  exit 1
                fi
              fi
            done

update:
  enabled: true
  release-monitor:
    identifier: 10037
