package:
  name: gomplate
  version: 4.0.1
  epoch: 1
  description: A go templating utility.
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - go
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 0738270366425af76becce44fa233c02506f90c9
      repository: https://github.com/hairyhenderson/gomplate
      tag: v${{package.version}}

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/bin
      go build -o ${{targets.destdir}}/usr/bin \
        -ldflags "-w -s -X github.com/hairyhenderson/gomplate/v4/version.Version=${{package.version}} \
        -X github.com/hairyhenderson/gomplate/v4/version.GitCommit=$(git rev-parse --short HEAD)" \
        github.com/hairyhenderson/gomplate/v4/cmd/gomplate

      # Test that the binary can be run, since there have been issues with the
      # Go version used by the tool that only manifest at runtime.
      ${{targets.destdir}}/usr/bin/gomplate -i 'the answer is: {{ mul 6 7 }}'

update:
  enabled: true
  github:
    identifier: hairyhenderson/gomplate
    strip-prefix: v
