package:
  name: goreleaser
  version: 2.0.1
  epoch: 3
  description: Deliver Go binaries as fast and easily as possible
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - git

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/goreleaser/goreleaser
      tag: v${{package.version}}
      expected-commit: 684c1805864e5f29acc204e34e1770eb74918d15

  - uses: go/bump
    with:
      deps: github.com/Azure/azure-sdk-for-go/sdk/azidentity@v1.6.0 github.com/hashicorp/go-retryablehttp@v0.7.7
      modroot: .

  - uses: go/build
    with:
      packages: .
      modroot: .
      output: goreleaser
      ldflags: -X main.version=${{package.version}} -X main.commit=$(git rev-parse HEAD) -X main.date=$(date ${SOURCE_DATE_EPOCH:+ -d@${SOURCE_DATE_EPOCH}} "+%Y-%m-%dT%H:%M:%SZ")

update:
  enabled: true
  github:
    identifier: goreleaser/goreleaser
    strip-prefix: v
