package:
  name: graphicsmagick
  version: "1.3.43"
  epoch: 0
  description: GraphicsMagick Image Processing Syste,
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - freetype-dev
      - libltdl
      - libpng-dev
      - libtool
      - libwebp-dev
      - libxml2-dev
      - tiff-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: 2b88580732cd7e409d9e22c6116238bef4ae06fcda11451bf33d259f9cbf399f
      uri: https://sourceforge.net/projects/graphicsmagick/files/graphicsmagick/${{package.version}}/GraphicsMagick-${{package.version}}.tar.xz

  - uses: autoconf/configure
    with:
      opts: |
        --with-quantum-depth=16 \
        --with-gs-font-dir=/usr/share/fonts/Type1 \
        --with-ttf \
        --with-webp

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: graphicsmagick-doc
    pipeline:
      - uses: split/manpages

  - name: graphicsmagick-cpp
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/lib
          mv ${{targets.destdir}}/usr/lib/libGraphicsMagick++.* ${{targets.subpkgdir}}/usr/lib/

  - name: graphicsmagick-dev
    pipeline:
      - uses: split/dev

update:
  release-monitor:
    identifier: 1248

test:
  pipeline:
    - runs: |
        gm help
        gm version | grep ${{package.version}}
