package:
  name: helm
  version: 3.15.2
  epoch: 1
  description: The Kubernetes Package Manager
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/helm/helm
      tag: v${{package.version}}
      expected-commit: 1a500d5625419a524fdae4b33de351cc4f58ec35

  - runs: |
      make build
      install -Dm755 ./bin/helm "${{targets.contextdir}}/usr/bin/helm"

  - uses: strip

test:
  pipeline:
    - runs: |
        helm version || exit 1
    - runs: |
        helm create test

update:
  enabled: true
  github:
    identifier: helm/helm
    strip-prefix: v
