package:
  name: hugo
  version: 0.128.1
  epoch: 1
  description: The world's fastest framework for building websites.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - git

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/gohugoio/hugo
      tag: v${{package.version}}
      expected-commit: 0ff542b4b9cc7b5cb425bbab8bdb5aace81d0c03

  - uses: go/bump
    with:
      deps: github.com/Azure/azure-sdk-for-go/sdk/azidentity@v1.6.0 golang.org/x/image@v0.18.0

  - uses: go/build
    with:
      packages: .
      output: hugo

  - uses: strip

update:
  enabled: true
  github:
    identifier: gohugoio/hugo
    strip-prefix: v
