package:
  name: istio-operator-1.22
  version: 1.22.2
  epoch: 1
  description: Istio operator provides user friendly options to operate the Istio service mesh
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - istio-operator=${{package.full-version}}

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/istio/istio
      tag: ${{package.version}}
      expected-commit: 204da5ba47f295a8dc56936333e692f6a8707649

  - uses: go/build
    with:
      packages: ./operator/cmd/operator
      output: operator

  - runs: |
      mkdir -p ${{targets.destdir}}/var/lib/istio
      mv manifests ${{targets.destdir}}/var/lib/istio/manifests

  - uses: strip

update:
  enabled: true
  ignore-regex-patterns:
    - '-rc'
    - '-beta'
  github:
    identifier: istio/istio
    tag-filter-prefix: 1.22.
    use-tag: true
