package:
  name: ntpd-rs
  version: 1.1.3
  epoch: 0
  description: "An NTP implementation in Rust."
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - rust
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pendulum-project/ntpd-rs
      tag: v${{package.version}}
      expected-commit: 7afb94163cac14a76f266e020c6405a48cacbf63

  - name: Configure and build
    runs: |
      cargo build --release -vv
      install -Dm755 target/release/ntp-daemon ${{targets.destdir}}/usr/bin/ntp-daemon
      install -Dm755 target/release/ntp-ctl ${{targets.destdir}}/usr/bin/ntp-ctl
      install -Dm755 target/release/ntp-metrics-exporter ${{targets.destdir}}/usr/bin/ntp-metrics-exporter

  - uses: strip

update:
  enabled: true
  github:
    identifier: pendulum-project/ntpd-rs
    strip-prefix: v

test:
  pipeline:
    - name: Check ntpd-rs version
      runs: |
        ntp-daemon --version
    - name: Validate ntpd-rs config
      runs: |
        ntp-ctl validate
