package:
  name: py3-trove-classifiers
  version: 2024.7.2
  epoch: 0
  description: Canonical source for classifiers on PyPI (pypi.org).
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-pip
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pypa/trove-classifiers
      expected-commit: 57bab905c6d601a907a56a082fc7564550faafb1
      tag: ${{package.version}}

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: pypa/trove-classifiers
