package:
  name: rust-analyzer
  version: 2024-01-22
  epoch: 0
  description: A Rust compiler front-end for IDEs
  copyright:
    - license: MIT or Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cargo-auditable
      - mimalloc2-dev
      - rust

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/rust-lang/rust-analyzer
      tag: ${{package.version}}
      expected-commit: d410d4a2baf9e99b37b03dd42f06238b14374bf7

  - runs: |
      CFG_RELEASE="${{package.version}}"
      cargo auditable build \
        --release \
        --features="mimalloc"

      install -Dm755 target/release/rust-analyzer -t "${{targets.destdir}}"/usr/bin/

  - uses: strip

subpackages:
  - name: ${{package.name}}-doc
    description: Documentation for ${{package.name}}
    pipeline:
      - runs: |
          install -Dm644 docs/user/manual.adoc -t "${{targets.subpkgdir}}"/usr/share/doc/${{package.name}}/

update:
  enabled: true
  ignore-regex-patterns:
    - 'nightly'
  github:
    identifier: rust-lang/rust-analyzer
