package:
  name: syft
  version: 1.8.0
  epoch: 1
  description: CLI tool and library for generating a Software Bill of Materials from container images and filesystems
  copyright:
    - license: Apache-2.0

environment:
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/anchore/syft
      tag: v${{package.version}}
      expected-commit: 1eae9333a9450c135ff929578597c79b01c9f5ff

  - uses: go/build
    with:
      ldflags: -X main.version=${{package.version}}
      output: syft
      packages: ./cmd/syft

  - uses: strip

update:
  enabled: true
  github:
    identifier: anchore/syft
    strip-prefix: v

test:
  pipeline:
    - runs: |
        syft --version
