package:
  name: temporal-ui-server
  version: 2.27.3
  epoch: 1
  description: Golang Server for https://github.com/temporalio/ui
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/temporalio/ui-server
      tag: v${{package.version}}
      expected-commit: 6291c3e8e71876fa91609614a03d3e2d630d60e6

  - uses: go/build
    with:
      packages: ./cmd/server
      output: ui-server
      ldflags: -s -w

  - uses: strip

subpackages:
  - name: temporal-ui-server-oci-entrypoint
    description: Entrypoint for using temporal ui-server in OCI containers
    dependencies:
      runtime:
        - bash
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/home/ui-server/
          cp docker/start-ui-server.sh ${{targets.subpkgdir}}/home/ui-server/
          chmod +x ${{targets.subpkgdir}}/home/ui-server/start-ui-server.sh

          mkdir -p ${{targets.subpkgdir}}/home/ui-server/config
          cp docker/config-template.yaml ${{targets.subpkgdir}}/home/ui-server/

          ln -s /usr/bin/ui-server ${{targets.subpkgdir}}/home/ui-server/ui-server

update:
  enabled: true
  github:
    identifier: temporalio/ui-server
    strip-prefix: v
    tag-filter: v
