package:
  name: test
  version: "0.0.1"
  epoch: 0
  description: Test package for env investigation
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle

pipeline:
  - runs: |
      whoami
      echo "HOME is set to: $HOME"
      echo "Current user is: $(id -u -n)"
      cat /etc/passwd

test:
  pipeline:
    - runs: |
        whoami
        echo "HOME is set to: $HOME"
        echo "Current user is: $(id -u -n)"
        cat /etc/passwd
