package:
  name: wolfictl
  version: 0.19.2
  epoch: 1
  description: Helper CLI for managing Wolfi
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/wolfi-dev/wolfictl
      tag: v${{package.version}}
      expected-commit: 87c018ae003839cd2fe12556ced2dcc06edbbf5a

  - uses: go/build
    with:
      packages: .
      output: wolfictl

  - uses: strip

test:
  pipeline:
    - name: Verify wolfictl
      runs: |
        wolfictl version

update:
  enabled: true
  github:
    identifier: wolfi-dev/wolfictl
    strip-prefix: v
    use-tag: true
