package:
  name: ytt
  version: 0.49.1
  epoch: 1
  description: YAML templating tool that works on YAML structure instead of text
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 0ec43ae2802931b23af6e4355c40ec1fb306d44b
      repository: https://github.com/carvel-dev/ytt
      tag: v${{package.version}}

  - uses: go/build
    with:
      packages: ./cmd/ytt
      output: ytt
      ldflags: -X github.com/vmware-tanzu/carvel-ytt/pkg/version.Version=v${{package.version}}

  - uses: strip

update:
  enabled: true
  github:
    identifier: carvel-dev/ytt
    strip-prefix: v
